export const data = [
  {
    id: 1,
    title: "Realms",
    src: "/assets/realms/realms-cover.jpg",
    number: 8,
    slug: "/works/1",
    story:
      "A dive into the surreal — where ordinary settings twist and reality bends into imagination. These works are meant to challenge perception, inviting the viewer to see beyond what is familiar.",
    pictures: [
      "/assets/realms/realms1.jpg",
      "/assets/realms/realms2.jpg",
      "/assets/realms/realms3.jpg",
      "/assets/realms/realms4.jpg",
      "/assets/realms/realms5.jpg",
      "/assets/realms/realms6.jpg",
      "/assets/realms/realms7.jpg",
      "/assets/realms/realms8.jpg",
    ],
  },
  {
    id: 2,
    title: "Portraits",
    src: "/assets/portraits/portraits-cover.jpg",
    number: 11,
    slug: "/works/2",
    story:
      "Every face has a story and every glance holds a truth. These portraits capture fleeting emotions and intimate details, preserving raw expressions that words could never fully describe.",
    pictures: [
      "/assets/portraits/portraits1.jpg",
      "/assets/portraits/portraits2.jpg",
      "/assets/portraits/portraits3.jpg",
      "/assets/portraits/portraits5.jpg",
      "/assets/portraits/portraits6.jpg",
      "/assets/portraits/portraits7.jpg",
      "/assets/portraits/portraits8.jpg",
      "/assets/portraits/portraits9.jpg",
      "/assets/portraits/portraits10.jpg",
      "/assets/portraits/portraits11.jpg",
      "/assets/portraits/portraits12.jpg",
    ],
  },
  {
    id: 3,
    title: "Painterly",
    src: "/assets/painterly/painterly-cover.jpg",
    number: 7,
    slug: "/works/3",
    story:
      "Inspired by brushstrokes and classic artistry, these images merge photography with the feel of paintings. Through light, texture, and color, each frame becomes a living canvas",
    pictures: [
      "/assets/painterly/painterly-lucynder.jpg",
      "/assets/painterly/painterly-adams.jpg",
      "/assets/painterly/painterly-pauls-letter.jpg",
      "/assets/painterly/painterly-pauls-letter2.jpg",
      "/assets/painterly/painterly-rootie.jpg",
      "/assets/painterly/painterly-mirabel.jpg",
      "/assets/painterly/painterly-unknown.jpg",
    ],
  },
  {
    id: 4,
    title: "Graduation",
    src: "/assets/grad/graduation-cover.jpg",
    number: 14,
    slug: "/works/4",
    story:
      "Moments of achievement and transition, filled with pride, relief, and excitement for what's ahead. These shoots capture not just the cap and gown but the spirit of stepping boldly into the future.",
    pictures: [
      "/assets/grad/graduation1.jpg",
      "/assets/grad/graduation2.jpg",
      "/assets/grad/graduation3.jpg",
      "/assets/grad/graduation4.jpg",
      "/assets/grad/graduation5.jpg",
      "/assets/grad/graduation6.jpg",
      "/assets/grad/graduation7.jpg",
      "/assets/grad/graduation8.jpg",
      "/assets/grad/graduation9.jpg",
      "/assets/grad/graduation10.jpg",
      "/assets/grad/graduation11.jpg",
      "/assets/grad/graduation12.jpg",
      "/assets/grad/graduation13.jpg",
      "/assets/grad/graduation14.jpg",
    ],
  },
  {
    id: 5,
    title: "Mobile",
    src: "/assets/mobile/mobile-photo-cover.jpg",
    number: 4,
    slug: "/works/5",
    story:
      "Simple tools, profound stories. Using just a mobile lens, these images celebrate the dignity, resilience, and timeless wisdom etched in the faces of the elderly.",
    pictures: [
      "/assets/mobile/mobile-photo1.jpg",
      "/assets/mobile/mobile-photo2.jpg",
      "/assets/mobile/mobile-photo3.jpg",
      "/assets/mobile/mobile-photo4.jpg",
    ],
  },
  {
    id: 6,
    title: "Clients",
    src: "/assets/clients/clients-cover.jpg",
    number: 14,
    slug: "/works/6",
    stroy:
      "Every client has a vision, my role is to translate it into images that tell their story. From concept to final frame, these works reflect collaboration, trust, and creativity tailored to individual needs.",
    pictures: [
      "/assets/clients/clients1.jpg",
      "/assets/clients/clients2.jpg",
      "/assets/clients/clients3.jpg",
      "/assets/clients/clients4.jpg",
      "/assets/clients/clients5.jpg",
      "/assets/clients/clients6.jpg",
      "/assets/clients/clients7.jpg",
      "/assets/clients/clients8.jpg",
      "/assets/clients/clients9.jpg",
      "/assets/clients/clients10.jpg",
      "/assets/clients/clients11.jpg",
      "/assets/clients/clients12.jpg",
      "/assets/clients/clients13.jpg",
      "/assets/clients/clients14.jpg",
    ],
  },
  {
    id: 7,
    title: "Events",
    src: "/assets/events/events-cover.jpg",
    number: 5,
    slug: "/works/7",
    story:
      "Each photograph in this collection is a memory preserved — the laughter, the quiet tears, and the moments that linger long after the celebration ends.",
    pictures: [
      "/assets/events/events1.jpg",
      "/assets/events/events2.jpg",
      "/assets/events/events3.jpg",
      "/assets/events/events4.jpg",
      "/assets/events/events5.jpg",
    ],
  },
];

export const contactLinks = [
  {
    platform: "Twitter",
    link: "https://x.com/olawaleololade_?t=P8vfya2jVfrfquaUX3sEIQ&s=09",
  },
  {
    platform: "Instagram",
    link: "https://instagram.com/ololade_wale?igsh=OGo4dHNpb2hqbmtm",
  },
  {
    platform: "Tiktok",
    link: "https://tiktok.com/@olawale_ololade?_t=8qPslpNoBr4&_r=1",
  },
  { platform: "Mail", link: "mailto:olawaleololade08@gmail.com" },
];
