export const data = [
  {
    id: 1,
    title: "Realms",
    src: "/assets/realms/realms-cover.jpg",
    number: 8,
    slug: "/works/1",
    pictures: [
      "/assets/realms/realms1.jpg",
      "/assets/realms/realms2.jpg",
      "/assets/realms/realms3.jpg",
      "/assets/realms/realms4.jpg",
      "/assets/realms/realms5.jpg",
      "/assets/realms/realms6.jpg",
      "/assets/realms/realms7.jpg",
      "/assets/realms/realms8.jpg",
    ],
  },
  {
    id: 2,
    title: "Portraits",
    src: "/assets/portraits/portraits-cover.jpg",
    number: 11,
    slug: "/works/2",
    pictures: [
      "/assets/portraits/portraits1.jpg",
      "/assets/portraits/portraits2.jpg",
      "/assets/portraits/portraits3.jpg",
      "/assets/portraits/portraits5.jpg",
      "/assets/portraits/portraits6.jpg",
      "/assets/portraits/portraits7.jpg",
      "/assets/portraits/portraits8.jpg",
      "/assets/portraits/portraits9.jpg",
      "/assets/portraits/portraits10.jpg",
      "/assets/portraits/portraits11.jpg",
      "/assets/portraits/portraits12.jpg",
    ],
  },
  {
    id: 3,
    title: "Painterly",
    src: "/assets/painterly/painterly-cover.jpg",
    number: 7,
    slug: "/works/3",
    pictures: [
      "/assets/painterly/painterly-lucynder.jpg",
      "/assets/painterly/painterly-adams.jpg",
      "/assets/painterly/painterly-pauls-letter.jpg",
      "/assets/painterly/painterly-pauls-letter2.jpg",
      "/assets/painterly/painterly-rootie.jpg",
      "/assets/painterly/painterly-mirabel.jpg",
      "/assets/painterly/painterly-unknown.jpg",
    ],
  },
  {
    id: 4,
    title: "Graduation",
    src: "/assets/grad/graduation-cover.jpg",
    number: 14,
    slug: "/works/4",
    pictures: [
      "/assets/grad/graduation1.jpg",
      "/assets/grad/graduation2.jpg",
      "/assets/grad/graduation3.jpg",
      "/assets/grad/graduation4.jpg",
      "/assets/grad/graduation5.jpg",
      "/assets/grad/graduation6.jpg",
      "/assets/grad/graduation7.jpg",
      "/assets/grad/graduation8.jpg",
      "/assets/grad/graduation9.jpg",
      "/assets/grad/graduation10.jpg",
      "/assets/grad/graduation11.jpg",
      "/assets/grad/graduation12.jpg",
      "/assets/grad/graduation13.jpg",
      "/assets/grad/graduation14.jpg",
    ],
  },
  {
    id: 5,
    title: "Mobile",
    src: "/assets/mobile/mobile-photo-cover.jpg",
    number: 4,
    slug: "/works/5",
    pictures: [
      "/assets/mobile/mobile-photo1.jpg",
      "/assets/mobile/mobile-photo2.jpg",
      "/assets/mobile/mobile-photo3.jpg",
      "/assets/mobile/mobile-photo4.jpg",
    ],
  },
  {
    id: 6,
    title: "Clients",
    src: "/assets/clients/clients-cover.jpg",
    number: 14,
    slug: "/works/6",
    pictures: [
      "/assets/clients/clients1.jpg",
      "/assets/clients/clients2.jpg",
      "/assets/clients/clients3.jpg",
      "/assets/clients/clients4.jpg",
      "/assets/clients/clients5.jpg",
      "/assets/clients/clients6.jpg",
      "/assets/clients/clients7.jpg",
      "/assets/clients/clients8.jpg",
      "/assets/clients/clients9.jpg",
      "/assets/clients/clients10.jpg",
      "/assets/clients/clients11.jpg",
      "/assets/clients/clients12.jpg",
      "/assets/clients/clients13.jpg",
      "/assets/clients/clients14.jpg",
    ],
  },
  {
    id: 7,
    title: "Events",
    src: "/assets/events/events-cover.jpg",
    number: 5,
    slug: "/works/7",
    pictures: [
      "/assets/events/events1.jpg",
      "/assets/events/events2.jpg",
      "/assets/events/events3.jpg",
      "/assets/events/events4.jpg",
      "/assets/events/events5.jpg",
    ],
  },
];
